sudo: required
language: minimal

git:
  depth: 2

branches:
  only:
  - master
  - devel

services:
  - docker

env:
  global:
    - IMAGE_REPO=gcr.io/dd-decaf-cfbf6/warehouse
    - IMAGE_TAG=${TRAVIS_BRANCH}

install:
  - docker build -t ${IMAGE_REPO}:${TRAVIS_COMMIT::12} -t ${IMAGE_REPO}:${TRAVIS_BRANCH} .
  - make databases

script:
  - make start
  - make upgrade
  - make fixture
  - make test-travis

before_deploy:
  - ./scripts/install_gcloud.sh
  - ./scripts/install_kubectl.sh
  - docker push ${IMAGE_REPO}:${TRAVIS_COMMIT::12}
  - docker push ${IMAGE_REPO}:${TRAVIS_BRANCH}

deploy:
  provider: script
  script: ./scripts/deploy.sh
  on:
    all_branches: true

notifications:
  email: false
  slack:
    rooms:
      secure: "BtVBsicAL6s/bz0lxAKYABjIq87G8ZsYqJuKkn+NdnA5n3eJIb91AguHH3f/wsW8/VHTr1Ccy5B+YLN2rVn68NA8yyM94HTQNT0kn3xpX/L06aw4jzqYLYhdleSG0xf4WkFL5JdCN8ompa5VHFW1B2bkhe49G7v43QO8++CGB4lW6JS2laXdyxW6EkwAL4BMdSv+atixbFTuFzKSTudx3KQVcmP0Q3TxN65iwdD4O74ruL79agj0bGQmHC/Z/6DouQoc7ycN83VI0ka+VwcviBXqu8FhTrzgiVnu7jRH7XhDkt88Z2I0aOkyjt7yPq3dy6m2nvRPa2DWpPveHB7zicNZz2El3jCwgNzU8POK+lLw8kFitJpuDuMFxIgDq20y0hrqUCmuEjogtIPV7d0z+eDPLaq1iCXq7J2D5RPRVsH5/Zkpx+2oeb2D0jKojgaD/Yc7psJo2LEIprONQghYpZYmFHXD4gythXGYhnlJEbMprTNk2gE5p2w7tUlOuqodJTTcAEIouWqLTO3aHq0M3PZNGc6JXp/Y93+KcqTFwyLSKTPqoVMcQXMa/sSAOhyWmMblCuwTAxSwsSGf4jeVNQOWeJEOnNkrs2ORkFuoCN07KvvIMEbP25HkF6j4v6RnA1lhAJl/Z1BHAmY2zlFv85HDJm7wfOsQyQJERcDkxgI="
    on_success: change
    on_failure: change
    on_pull_requests: false
