os: linux
language: shell

git:
  depth: 2

branches:
  only:
  - master
  - devel

services:
- docker

env:
  global:
  - IMAGE=gcr.io/dd-decaf-cfbf6/warehouse
  - BRANCH=${TRAVIS_BRANCH}
  - BUILD_COMMIT=${TRAVIS_COMMIT}
  - SHORT_COMMIT=${TRAVIS_COMMIT:0:7}
  - BUILD_TIMESTAMP=$(date --utc --iso-8601=seconds)
  - BUILD_DATE=$(date --utc --iso-8601=date)
  - BUILD_TAG=${BRANCH}_${BUILD_DATE}_${SHORT_COMMIT}

before_install:
- make setup

install:
- make build-travis
- make build
- make post-build
- make start

script:
- make style
- make safety
# Run the tests and report coverage (see https://docs.codecov.io/docs/testing-with-docker).
- docker-compose exec -e ENVIRONMENT=testing web pytest --cov=warehouse --cov-report=term --cov-report=xml
- bash <(curl -s https://codecov.io/bash)

before_deploy:
- ./scripts/install_gcloud.sh
- ./scripts/install_kubectl.sh
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then make push; fi

deploy:
  provider: script
  script: ./scripts/deploy.sh
  on:
    all_branches: true

notifications:
  email: false
  slack:
    rooms:
      secure: "BtVBsicAL6s/bz0lxAKYABjIq87G8ZsYqJuKkn+NdnA5n3eJIb91AguHH3f/wsW8/VHTr1Ccy5B+YLN2rVn68NA8yyM94HTQNT0kn3xpX/L06aw4jzqYLYhdleSG0xf4WkFL5JdCN8ompa5VHFW1B2bkhe49G7v43QO8++CGB4lW6JS2laXdyxW6EkwAL4BMdSv+atixbFTuFzKSTudx3KQVcmP0Q3TxN65iwdD4O74ruL79agj0bGQmHC/Z/6DouQoc7ycN83VI0ka+VwcviBXqu8FhTrzgiVnu7jRH7XhDkt88Z2I0aOkyjt7yPq3dy6m2nvRPa2DWpPveHB7zicNZz2El3jCwgNzU8POK+lLw8kFitJpuDuMFxIgDq20y0hrqUCmuEjogtIPV7d0z+eDPLaq1iCXq7J2D5RPRVsH5/Zkpx+2oeb2D0jKojgaD/Yc7psJo2LEIprONQghYpZYmFHXD4gythXGYhnlJEbMprTNk2gE5p2w7tUlOuqodJTTcAEIouWqLTO3aHq0M3PZNGc6JXp/Y93+KcqTFwyLSKTPqoVMcQXMa/sSAOhyWmMblCuwTAxSwsSGf4jeVNQOWeJEOnNkrs2ORkFuoCN07KvvIMEbP25HkF6j4v6RnA1lhAJl/Z1BHAmY2zlFv85HDJm7wfOsQyQJERcDkxgI="
    on_success: change
    on_failure: change
    on_pull_requests: false
