version: "3.1"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BASE_TAG=${BASE_TAG}
        - BUILD_COMMIT=${BUILD_COMMIT:-unknown}
        - BUILD_TIMESTAMP=${BUILD_TIMESTAMP:-unknown}
    image: gcr.io/dd-decaf-cfbf6/warehouse:${IMAGE_TAG:-latest}
    depends_on:
      - postgres
    networks:
      default:
      DD-DeCaF:
        aliases:
          - warehouse
    ports:
      - "${API_PORT:-8000}:8000"
    volumes:
      - ".:/app"
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - SCRIPT_NAME=${SCRIPT_NAME}
      - FLASK_APP=src/warehouse/wsgi.py
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-http://localhost:4200}
      - SENTRY_DSN=${SENTRY_DSN}
      - POSTGRES_HOST=${POSTGRES_HOST:-postgres}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_DB_NAME=${POSTGRES_DB_NAME:-postgres}
      - POSTGRES_ENV_USERNAME=${POSTGRES_ENV_USERNAME:-postgres}
      - POSTGRES_ENV_PASS=${POSTGRES_ENV_PASS:-secret}
      - BASIC_AUTH_USERNAME=${BASIC_AUTH_USERNAME}
      - BASIC_AUTH_PASSWORD=${BASIC_AUTH_PASSWORD}
      - IAM_API=https://api-staging.dd-decaf.eu/iam
    command: ["/bin/sh","-c","FLASK_APP=src/warehouse/wsgi.py flask db upgrade && gunicorn -c gunicorn.py warehouse.wsgi:app"]
  postgres:
    image: postgres:9.6-alpine
    ports:
      - "${PG_PORT:-5432}:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_ENV_PASS:-secret}
    networks:
      - default


# Additional services that the `web` service `depends_on` should usually only
# be on the default network and not exposed on the general network, i.e.,
# networks:
#   - default

networks:
  DD-DeCaF:
    external: true
