"""initial

Revision ID: 1336b7c4b1b5
Revises: 
Create Date: 2018-04-16 16:49:53.694807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1336b7c4b1b5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strain',
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('genotype', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['strain.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('strain')
    # ### end Alembic commands ###
