"""timestamp

Revision ID: 187535fa2942
Revises: 39fad0f074d4
Create Date: 2018-06-11 11:38:26.890198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '187535fa2942'
down_revision = '39fad0f074d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('biological_entity', sa.Column('created', sa.DateTime(), nullable=False))
    op.add_column('biological_entity', sa.Column('updated', sa.DateTime(), nullable=True))
    op.add_column('biological_entity_type', sa.Column('created', sa.DateTime(), nullable=False))
    op.add_column('biological_entity_type', sa.Column('updated', sa.DateTime(), nullable=True))
    op.add_column('experiment', sa.Column('created', sa.DateTime(), nullable=False))
    op.add_column('experiment', sa.Column('updated', sa.DateTime(), nullable=True))
    op.add_column('measurement', sa.Column('created', sa.DateTime(), nullable=False))
    op.add_column('measurement', sa.Column('updated', sa.DateTime(), nullable=True))
    op.add_column('medium', sa.Column('created', sa.DateTime(), nullable=False))
    op.add_column('medium', sa.Column('updated', sa.DateTime(), nullable=True))
    op.add_column('medium_compound', sa.Column('created', sa.DateTime(), nullable=False))
    op.add_column('medium_compound', sa.Column('updated', sa.DateTime(), nullable=True))
    op.add_column('namespace', sa.Column('created', sa.DateTime(), nullable=False))
    op.add_column('namespace', sa.Column('updated', sa.DateTime(), nullable=True))
    op.add_column('organism', sa.Column('created', sa.DateTime(), nullable=False))
    op.add_column('organism', sa.Column('updated', sa.DateTime(), nullable=True))
    op.add_column('sample', sa.Column('created', sa.DateTime(), nullable=False))
    op.add_column('sample', sa.Column('updated', sa.DateTime(), nullable=True))
    op.add_column('strain', sa.Column('created', sa.DateTime(), nullable=False))
    op.add_column('strain', sa.Column('updated', sa.DateTime(), nullable=True))
    op.add_column('unit', sa.Column('created', sa.DateTime(), nullable=False))
    op.add_column('unit', sa.Column('updated', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('unit', 'updated')
    op.drop_column('unit', 'created')
    op.drop_column('strain', 'updated')
    op.drop_column('strain', 'created')
    op.drop_column('sample', 'updated')
    op.drop_column('sample', 'created')
    op.drop_column('organism', 'updated')
    op.drop_column('organism', 'created')
    op.drop_column('namespace', 'updated')
    op.drop_column('namespace', 'created')
    op.drop_column('medium_compound', 'updated')
    op.drop_column('medium_compound', 'created')
    op.drop_column('medium', 'updated')
    op.drop_column('medium', 'created')
    op.drop_column('measurement', 'updated')
    op.drop_column('measurement', 'created')
    op.drop_column('experiment', 'updated')
    op.drop_column('experiment', 'created')
    op.drop_column('biological_entity_type', 'updated')
    op.drop_column('biological_entity_type', 'created')
    op.drop_column('biological_entity', 'updated')
    op.drop_column('biological_entity', 'created')
    # ### end Alembic commands ###
