"""feed_medium

Revision ID: 2b9e88a6b228
Revises: 187535fa2942
Create Date: 2018-06-26 07:30:26.689374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b9e88a6b228'
down_revision = '187535fa2942'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('measurement', 'numerator_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('sample', sa.Column('feed_medium_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sample', 'medium', ['feed_medium_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sample', type_='foreignkey')
    op.drop_column('sample', 'feed_medium_id')
    op.alter_column('measurement', 'numerator_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
