"""aerobic

Revision ID: 39fad0f074d4
Revises: c4d790edc9f7
Create Date: 2018-05-23 16:47:49.439875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39fad0f074d4'
down_revision = 'c4d790edc9f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sample', sa.Column('aerobic', sa.Boolean(), nullable=False))
    op.drop_column('sample', 'gas')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sample', sa.Column('gas', sa.VARCHAR(length=256), autoincrement=False, nullable=False))
    op.drop_column('sample', 'aerobic')
    # ### end Alembic commands ###
