"""organism_medium

Revision ID: 441fd74cfebd
Revises: 1336b7c4b1b5
Create Date: 2018-04-18 14:12:33.279366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '441fd74cfebd'
down_revision = '1336b7c4b1b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('biological_entity_type',
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medium',
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('ph', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('namespace',
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organism',
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('biological_entity',
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('namespace_id', sa.Integer(), nullable=True),
    sa.Column('reference', sa.String(length=256), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['namespace_id'], ['namespace.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['biological_entity_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medium_compound',
    sa.Column('medium_id', sa.Integer(), nullable=False),
    sa.Column('compound_id', sa.Integer(), nullable=False),
    sa.Column('mass_concentration', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['compound_id'], ['biological_entity.id'], ),
    sa.ForeignKeyConstraint(['medium_id'], ['medium.id'], ),
    sa.PrimaryKeyConstraint('medium_id', 'compound_id')
    )
    op.add_column('strain', sa.Column('organism_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'strain', 'organism', ['organism_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'strain', type_='foreignkey')
    op.drop_column('strain', 'organism_id')
    op.drop_table('medium_compound')
    op.drop_table('biological_entity')
    op.drop_table('organism')
    op.drop_table('namespace')
    op.drop_table('medium')
    op.drop_table('biological_entity_type')
    # ### end Alembic commands ###
