"""empty message

Revision ID: 468f4d9b6b05
Revises: d5db53144449
Create Date: 2020-01-15 12:59:34.655925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '468f4d9b6b05'
down_revision = 'd5db53144449'
branch_labels = None
depends_on = None

# Table for data migration
sample = sa.sql.table('sample', sa.Column('name', sa.Text()))

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sample', sa.Column('name', sa.Text(), nullable=True))
    # ### end Alembic commands ###
    # Update existing rows with default value for name
    op.execute(sample.update().values({"name": "Unknown"}))
    op.alter_column('sample', 'name', existing_type=sa.TEXT(), nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sample', 'name')
    # ### end Alembic commands ###
