"""backref

Revision ID: 7a18282a656f
Revises: 45e0fc5c182a
Create Date: 2018-05-08 14:39:20.651337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a18282a656f'
down_revision = '45e0fc5c182a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
