"""add name column

Revision ID: b11dc26220c0
Revises: 167bb88c5da9
Create Date: 2019-11-25 11:50:42.376003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b11dc26220c0'
down_revision = '167bb88c5da9'
branch_labels = None
depends_on = None

# Table for data migration
proteomics = sa.sql.table('proteomics', sa.Column('name', sa.Text()))


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proteomics', sa.Column('name', sa.Text(), nullable=True))
    # Update existing rows with default value for name
    op.execute(proteomics.update().values({"name": "Unknown"}))
    op.alter_column('proteomics', 'name', existing_type=sa.TEXT(), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proteomics', 'name')
    # ### end Alembic commands ###
