"""nullable

Revision ID: c4d790edc9f7
Revises: 7a18282a656f
Create Date: 2018-05-08 15:13:49.260846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4d790edc9f7'
down_revision = '7a18282a656f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('measurement', 'denominator_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('measurement', 'denominator_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
