"""chemical_name

Revision ID: ce0b8c0ec29d
Revises: 2b9e88a6b228
Create Date: 2018-06-26 10:06:41.152558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce0b8c0ec29d'
down_revision = '2b9e88a6b228'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('biological_entity', 'name',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=2048),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('biological_entity', 'name',
               existing_type=sa.String(length=2048),
               type_=sa.VARCHAR(length=256),
               existing_nullable=False)
    # ### end Alembic commands ###
